services:
  - type: web
    name: student-data-api
    env: python
    buildCommand: ""
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: DATABASE_URL
        value: mysql+pymysql://root:rahul123@localhost:3306/student-db-collection
